# -*- coding: utf-8 -*-
"""Perceptron 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m4IhSJ78WjVegkHo22ldqUDbPrxyILV2

# Perceptron 2

## Inputs and weights
"""

import numpy as np

inputs = np.array([35, 25])

type(inputs)

weights = np.array([-0.8, 0.1])

"""## Sum function"""

def sum(inputs, weights):
  return inputs.dot(weights)

s = sum(inputs, weights)

s

"""## Step function"""

def step_function(sum):
  if (sum >= 1):
    return 1
  return 0

"""## Final result"""

step_function(s)