# -*- coding: utf-8 -*-
"""Homework solution TensorFlow: Fashion MNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xHYWjixSQCguQKyP0JcfZxS3ShQd6H5W

# Homework solution TensorFlow: Fashion MNIST

https://www.kaggle.com/zalando-research/fashionmnist

## Loading the dataset
"""

import tensorflow
tensorflow.__version__

import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.datasets import fashion_mnist

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

i = np.random.randint(0, len(X_train))
plt.imshow(X_train[i], cmap = 'gray')
plt.title('Class ' + str(y_train[i]))

X_train.shape

X_train = X_train.reshape(60000, 28 * 28)
X_train.shape

X_train[0]

X_test.shape

X_test = X_test.reshape(10000, 28 * 28)
X_test.shape

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train /= 255
X_test /= 255

X_train.max()

X_train.min()

y_train

"""## Neural network (training)"""

(784 + 10) / 2

network = Sequential()
network.add(Dense(input_shape = (784,), units = 397, activation = 'relu'))
network.add(Dense(units = 397, activation = 'relu'))
network.add(Dense(units = 10, activation = 'softmax'))

network.compile(loss = 'sparse_categorical_crossentropy', 
                      optimizer = 'adam', 
                      metrics = ['accuracy'])

history = network.fit(X_train, y_train, batch_size = 128, epochs = 10)

"""## Neural network (evaluation)"""

history.history.keys()

plt.plot(history.history['loss'])

plt.plot(history.history['accuracy'])

accuracy_test = network.evaluate(X_test, y_test)

predictions = network.predict(X_test)

predictions[0]

np.argmax(predictions[0])

plt.imshow(X_test[0].reshape(28, 28), cmap = 'gray')
plt.title('Class ' + str(y_test[0]))