# -*- coding: utf-8 -*-
"""Perceptron AND operator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ovTlI6K5tvdsEv5rxHK4d9sez0OyU_b-

# Perceptron AND operator

![alt text](https://drive.google.com/uc?id=1EVKYuVhLOMcvCOo4x2WDe9-rzbsIqe47)

## Inputs, outputs and weights
"""

import numpy as np

inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

inputs.shape

outputs = np.array([0, 0, 0, 1])

outputs.shape

weights = np.array([0.0, 0.0])

learning_rate = 0.1

"""## Step function"""

def step_function(sum):
  if (sum >= 1):
    return 1
  return 0

"""## Calculate output"""

def calculate_output(instance):
  s = instance.dot(weights)
  return step_function(s)

calculate_output(np.array([[1,1]]))

"""## Train"""

len(outputs)

inputs[3]

0 - 1

abs(0 - 1)

inputs

inputs[1]

inputs[1][0]

inputs[1][1]

def train():
  total_error = 1
  while (total_error != 0):
    total_error = 0
    for i in range(len(outputs)):
      prediction = calculate_output(inputs[i])
      error = abs(outputs[i] - prediction)
      total_error += error
      if error > 0:
        for j in range(len(weights)):
          weights[j] = weights[j] + (learning_rate * inputs[i][j] * error)
          print('Weight updated: ' + str(weights[j]))
    print('Total error: ' + str(total_error))

train()

"""## Classification"""

weights

calculate_output(np.array([0,0]))

calculate_output(np.array([0,1]))

calculate_output(np.array([1,0]))

calculate_output(np.array([1,1]))