# -*- coding: utf-8 -*-
"""Libraries for Neural Networks - sklearn 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lbGiUqYh43GlXt0-WlFOgVqIMouah9L

# Libraries for Neural Networks - sklearn 1 (classification)


![alt text](https://drive.google.com/uc?id=1xgZhek0467AtlfupqvovcjoFIJ2dB4in)

## Loading the data
"""

from sklearn.neural_network import MLPClassifier
from sklearn import datasets

iris = datasets.load_iris()

inputs = iris.data
inputs

iris.feature_names

outputs = iris.target
outputs

iris.target_names

inputs.shape

outputs.shape

"""## Train and test datasets"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, outputs, test_size = 0.2)

X_train.shape

y_train.shape

X_test.shape

y_test.shape

X_train[0:5]

X_test[0:5]

y_train[0:5]

y_test[0:5]

"""## Neural network (training)"""

network = MLPClassifier(max_iter=2000, 
                        verbose=True,
                        tol=0.0000100,
                        activation = 'logistic',
                        solver = 'adam',
                        learning_rate = 'constant',
                        learning_rate_init = 0.001,
                        batch_size = 32,
                        hidden_layer_sizes = (4, 5)
                        #early_stopping = True,
                        #n_iter_no_change = 50
                        )
network.fit(X_train, y_train)

0.06410639 - 0.06401348

network.classes_

network.coefs_

network.intercepts_

network.n_layers_

network.n_outputs_

network.out_activation_

"""## Neural network (evaluation)"""

X_test.shape

predictions = network.predict(X_test)
predictions

y_test

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, predictions)

cm = confusion_matrix(y_test, predictions)
cm

!pip install yellowbrick --upgrade

from yellowbrick.classifier import ConfusionMatrix
confusion_matrix = ConfusionMatrix(network, classes = iris.target_names)
confusion_matrix.fit(X_train, y_train)
confusion_matrix.score(X_test, y_test)
confusion_matrix.show()

"""## Neural network (classification)"""

X_test[0], y_test[0]

X_test[0].shape

new = X_test[0].reshape(1, -1)
new.shape

network.predict(new)

iris.target_names[network.predict(new)[0]]